//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 16 2019 10:33:12).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIControl.h"

#import "MMDragDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFacadeExt-Protocol.h"
#import "WCPlayerConfigViewControllerDelegate-Protocol.h"

@class FullScreenViewController, MMDragManager, NSString, SightIconView, UIDragInteraction, UIImageView, WCDataItem, WCMediaItem, WCPlayerInfo;
@protocol SNSVideoABTestExt, WCSNSNodeVideoViewDelegate;

@interface WCSNSNodeVideoView : MMUIControl <WCPlayerConfigViewControllerDelegate, WCActionSheetDelegate, WCFacadeExt, UIActionSheetDelegate, MMDragDelegate>
{
    _Bool _bIsLongPressHandled;
    WCDataItem *_dataItem;
    UIImageView *_thumbImageView;
    FullScreenViewController<SNSVideoABTestExt> *_videoPlayerVC;
    SightIconView *_playIconView;
    MMDragManager *dragManager;
    UIImageView *tmp_liftingImgView;
    UIDragInteraction *dragInteraction;
    WCPlayerInfo *_playerInfo;
    _Bool _isImageReady;
    _Bool _bIgnoreLongPress;
    id <WCSNSNodeVideoViewDelegate> _delegate;
    WCMediaItem *_mediaData;
    NSString *_sightPath;
    NSString *_cpKey;
    unsigned long long _scene;
}

- (void).cxx_destruct;
- (void)LongPressEvents:(id)arg1;//01B74600

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) _Bool bIgnoreLongPress; // @synthesize bIgnoreLongPress=_bIgnoreLongPress;
@property(retain, nonatomic) NSString *cpKey; // @synthesize cpKey=_cpKey;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
- (void)dealloc;
@property(nonatomic) __weak id <WCSNSNodeVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)generateFavWithMediaWrap:(id)arg1;
- (id)generateMsgWithMediaWrap:(id)arg1;
- (id)getImage;
- (id)getPlayerInfoWith:(_Bool)arg1;
- (unsigned long long)getWCDownloadModeWith:(unsigned long long)arg1;
- (void)initData:(id)arg1;
- (id)initWithMediaData:(id)arg1;
- (id)initWithMediaData:(id)arg1 withFrame:(struct CGRect)arg2;
@property(readonly, nonatomic) _Bool isImageReady; // @synthesize isImageReady=_isImageReady;
- (_Bool)isSightVideoExist;
- (void)layoutSubviews;
- (void)liftingImageNeedRemove;
- (id)liftingItemWithImage:(id)arg1 parameters:(id)arg2;
@property(readonly, nonatomic) WCMediaItem *mediaData; // @synthesize mediaData=_mediaData;
- (void)onClickWCSight:(id)arg1;
- (void)onCloseFullScreenPlay:(id)arg1;
- (void)onDownloadFail:(id)arg1 downloadType:(int)arg2;
- (void)onDownloadFinish:(id)arg1 downloadType:(int)arg2;
- (void)onForwardCancle:(id)arg1;
- (void)onForwardSuccess:(id)arg1;
- (void)onLongPress:(id)arg1;//    01B75000

- (void)onMediaItemSizeDidChange:(id)arg1;
- (void)onTapAttachButton:(id)arg1;
- (void)playInFullScreen:(_Bool)arg1;
- (void)reloadSightPreviewImage;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
- (void)setFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSString *sightPath; // @synthesize sightPath=_sightPath;
- (void)silencePlay;
- (void)updateThumbImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

