//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface OPPaymentVideoModel : NSObject
{
    _Bool _isLogin;
    NSDictionary *_sourceData;
    NSDictionary *_playEndInfo;
}

+ (_Bool)isLogin;
+ (id)createFromDictionary:(id)arg1;
@property(nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
@property(retain, nonatomic) NSDictionary *playEndInfo; // @synthesize playEndInfo=_playEndInfo;
@property(retain, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
- (void).cxx_destruct;

@end

