//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YKWeexView.h"

@class BaseLoadingView, UIView;

@interface OPPaymentVideoPlayerEndWeexView : YKWeexView
{
    CDUnknownBlockType _refreshBlock;
    UIView *_errorView;
    BaseLoadingView *_loadingView;
}

@property(retain, nonatomic) BaseLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIView *errorView; // @synthesize errorView=_errorView;
@property(copy, nonatomic) CDUnknownBlockType refreshBlock; // @synthesize refreshBlock=_refreshBlock;
- (void).cxx_destruct;
- (void)refreshAction;
- (void)setupGradientColor:(id)arg1;
- (void)onRenderFinish:(id)arg1;
- (void)onFailed:(id)arg1;
- (void)render;

@end

