//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 16 2019 10:33:12).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WCPayOrderPayConfirmViewDelegate <NSObject>
- (void)OnOrderPayChangeConpons;
- (void)onOrderPayChangeCard;
- (void)onOrderPayConfirmViewCancel;
- (void)onOrderPayConfirmViewGotoPasswordAuth;
- (void)onOrderPayConfirmViewGotoTouchIDAuth;
- (void)onOrderPayConfirmViewPay:(NSString *)arg1;
- (void)onOrderPayConfirmViewPerformTouchID;
@end

