//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ICScrollViewDelegateViewController.h"

#import "ICFolderListDelegate-Protocol.h"
#import "ICNoteContainerCellDelegate-Protocol.h"
#import "ICProgressIndicatorTrackerDelegate-Protocol.h"
#import "NSFetchedResultsControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AccountUtilities, ICListTableView, ICNotesListViewController, ICProgressIndicatorTracker, NSArray, NSFetchedResultsController, NSMutableArray, NSString, NoteCollectionListController, NotesBackgroundView, UIAlertController, UIBarButtonItem, UITableView;
@protocol ICFolderListDelegate;

@interface ICFolderListViewController : ICScrollViewDelegateViewController <NSFetchedResultsControllerDelegate, UITableViewDataSource, UITableViewDelegate, ICFolderListDelegate, ICNoteContainerCellDelegate, ICProgressIndicatorTrackerDelegate>
{
    BOOL _hideLegacyAccounts;
    BOOL _needTableViewReload;
    BOOL _recreateFetchedResultsControllerOnReload;
    BOOL _legacyAccountsAreSortedOnTop;
    BOOL _blockIncrementalUpdates;
    BOOL _viewSetupDeferred;
    BOOL _observingLegacyNoteContext;
    unsigned int _folderListMode;
    id <ICFolderListDelegate> _delegate;
    NSArray *_notesBeingMoved;
    ICNotesListViewController *_notesListViewController;
    NoteCollectionListController *_legacyNoteCollectionListController;
    NSFetchedResultsController *_fetchedResultsController;
    UIBarButtonItem *_addFolderButton;
    UIBarButtonItem *_editButton;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_flexibleSpaceItem;
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_cancelButton;
    UIBarButtonItem *_debugButton;
    ICListTableView *_tableView;
    unsigned int _beginTableViewUpdatesCount;
    NSMutableArray *_legacyStoreHierarchy;
    AccountUtilities *_accountUtilities;
    UIAlertController *_editTitleAlert;
    ICProgressIndicatorTracker *_progressIndicatorTracker;
}

+ (BOOL)legacyAccountsShouldBeOnTop;
+ (id)visibleLegacyAccountsCheckDisabled:(BOOL)arg1;
+ (id)visibleLegacyAccounts;
@property(nonatomic) BOOL observingLegacyNoteContext; // @synthesize observingLegacyNoteContext=_observingLegacyNoteContext;
@property(nonatomic) BOOL viewSetupDeferred; // @synthesize viewSetupDeferred=_viewSetupDeferred;
@property(retain, nonatomic) ICProgressIndicatorTracker *progressIndicatorTracker; // @synthesize progressIndicatorTracker=_progressIndicatorTracker;
@property(nonatomic) BOOL blockIncrementalUpdates; // @synthesize blockIncrementalUpdates=_blockIncrementalUpdates;
@property(nonatomic) __weak UIAlertController *editTitleAlert; // @synthesize editTitleAlert=_editTitleAlert;
@property(nonatomic) BOOL legacyAccountsAreSortedOnTop; // @synthesize legacyAccountsAreSortedOnTop=_legacyAccountsAreSortedOnTop;
@property(nonatomic) __weak AccountUtilities *accountUtilities; // @synthesize accountUtilities=_accountUtilities;
@property(retain, nonatomic) NSMutableArray *legacyStoreHierarchy; // @synthesize legacyStoreHierarchy=_legacyStoreHierarchy;
@property(nonatomic) BOOL recreateFetchedResultsControllerOnReload; // @synthesize recreateFetchedResultsControllerOnReload=_recreateFetchedResultsControllerOnReload;
@property(nonatomic) BOOL needTableViewReload; // @synthesize needTableViewReload=_needTableViewReload;
@property(nonatomic) unsigned int beginTableViewUpdatesCount; // @synthesize beginTableViewUpdatesCount=_beginTableViewUpdatesCount;
@property(retain, nonatomic) ICListTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIBarButtonItem *debugButton; // @synthesize debugButton=_debugButton;
@property(retain, nonatomic) UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIBarButtonItem *trashButton; // @synthesize trashButton=_trashButton;
@property(retain, nonatomic) UIBarButtonItem *flexibleSpaceItem; // @synthesize flexibleSpaceItem=_flexibleSpaceItem;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIBarButtonItem *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UIBarButtonItem *addFolderButton; // @synthesize addFolderButton=_addFolderButton;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(retain) NoteCollectionListController *legacyNoteCollectionListController; // @synthesize legacyNoteCollectionListController=_legacyNoteCollectionListController;
@property(retain) ICNotesListViewController *notesListViewController; // @synthesize notesListViewController=_notesListViewController;
@property(copy, nonatomic) NSArray *notesBeingMoved; // @synthesize notesBeingMoved=_notesBeingMoved;
@property(retain) id <ICFolderListDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL hideLegacyAccounts; // @synthesize hideLegacyAccounts=_hideLegacyAccounts;
@property(nonatomic) unsigned int folderListMode; // @synthesize folderListMode=_folderListMode;
- (void).cxx_destruct;
- (void)selectFirstModernAccount;
- (void)selectFirstLegacyAccount;
- (BOOL)accessibilityPerformEscape;
- (void)handleAccessibilityDarkenColorsChangedNotification:(id)arg1;
- (BOOL)_icaxDeleteSelectedFolders;
- (void)_icaxAnnounceCreatedFolder:(id)arg1;
- (void)_icaxAnnounceDeletedFolders:(id)arg1;
- (void)_icaxNoteContainerCellTitleWasTapped:(id)arg1;
@property(readonly, nonatomic) UITableView *_icaxTableView;
- (void)progressIndicatorTrackerStopAnimation;
- (void)progressIndicatorTrackerStartAnimation;
- (id)legacyAccountForTableViewSection:(unsigned int)arg1;
- (id)legacySectionInfoDictFromTableViewSectionIndex:(unsigned int)arg1;
- (unsigned int)legacySectionIndexFromTableViewSection:(unsigned int)arg1;
- (id)legacyNoteCollectionAtTableViewIndexPath:(id)arg1;
- (void)legacyNotesChanged;
- (void)reloadDataAfterLegacyChanges;
- (void)accountsUpdated:(id)arg1;
- (void)recreateLegacyHierarchy;
- (id)undoManager;
- (BOOL)canBecomeFirstResponder;
- (void)modernNotesChanged:(id)arg1;
- (void)reloadDataMaintainingSelection;
- (void)migrationStateDidChange:(id)arg1;
- (void)migrationStateWillChange:(id)arg1;
- (void)updateOrCopyLegacyAccount:(id)arg1;
- (unsigned int)sectionIndexFromButtonView:(id)arg1;
- (BOOL)shouldShowUpdateOrCopyButtonForLegacyAccount:(id)arg1 outIsPrimaryAccount:(char *)arg2;
- (void)applicationWillEnterForeground:(id)arg1;
- (BOOL)shouldDisableSelectionForNoteContainer:(id)arg1;
- (void)attachPalette;
- (BOOL)shouldShowPalette;
- (void)tearDownFetchedResultsController;
- (void)recreateFetchedResultsController;
- (void)deleteFolders:(id)arg1 movingNotesToUnsortedFolder:(BOOL)arg2;
- (void)promptToDeleteNonEmptyFolders:(id)arg1;
- (void)deleteFolders:(id)arg1;
- (void)contentSizeCategoryDidChange;
- (void)showNoteCollection:(id)arg1;
- (void)showNoteContainer:(id)arg1;
- (void)updateBarButtonsAnimated:(BOOL)arg1;
- (void)updateNavigationTitle;
- (id)cloudKitNoteContainerAtTableViewIndexPath:(id)arg1;
- (unsigned int)cloudKitSectionForFetchedResultsFromTableViewSection:(unsigned int)arg1;
- (id)indexPathForFolderInTableViewFromFetchedResultsControllerIndexPath:(id)arg1 managedObjectContext:(id)arg2;
- (void)promptToChooseAccountToAddFolderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)promptToAddFolderToAccount:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)promptToAddFolderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)editTitleTextFieldChanged:(id)arg1;
- (void)promptToEditTitle:(id)arg1 newFolder:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)showSingleButtonAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)promptToEditTitleForFolder:(id)arg1;
- (void)noteCollectionCellTitleWasTapped:(id)arg1;
- (void)noteContainerCellTitleWasTapped:(id)arg1;
- (void)prepareForSuspend;
- (BOOL)shouldAutorotate;
- (void)folderListDidCancel:(id)arg1;
- (void)folderList:(id)arg1 didSelectNoteCollection:(id)arg2 cellFrame:(struct CGRect)arg3;
- (void)folderList:(id)arg1 didSelectNoteContainer:(id)arg2;
- (void)reachabilityChanged:(id)arg1;
- (void)viewControllerWillStartEditModeNotification:(id)arg1;
- (void)notesContextRefreshNotification:(id)arg1;
- (void)accountsDidChange:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned int)arg3 forChangeType:(unsigned int)arg4;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerWillChangeContent:(id)arg1;
- (id)cloudKitManagedObjectContext;
- (id)legacyManagedObjectContext;
- (void)deleteSelectedFolders:(id)arg1;
- (void)endEditMode:(id)arg1;
- (void)startEditMode:(id)arg1;
- (BOOL)shouldEnableEditButton;
- (void)showDebugMenu:(id)arg1;
- (void)cancel:(id)arg1;
- (void)addFolder:(id)arg1;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)updateActivityIndicatorInAllSectionHeaderViews;
- (void)updateAllSectionHeaderViews;
- (void)updateActivityIndicatorInSectionHeaderView:(id)arg1 section:(unsigned int)arg2;
- (void)updateSectionHeaderView:(id)arg1 section:(unsigned int)arg2;
- (void)updateTitleForSectionHeaderView:(id)arg1 section:(unsigned int)arg2;
- (void)updateAccessoryViewForCellAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)cloudKitAccountFromTableViewSectionIndex:(unsigned int)arg1;
- (id)cloudKitSectionInfoFromTableViewSectionIndex:(unsigned int)arg1;
- (id)cellForNoteContainerAtIndexPath:(id)arg1;
- (id)cellForNewFolder;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldShowNewFolderItem;
- (void)deselectAll:(BOOL)arg1;
- (void)updateViewByReloadingAccounts;
- (void)splitViewControllerDidChangeHorizontalSizeClass:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)contentScrollView;
@property(readonly, nonatomic) NotesBackgroundView *backgroundView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

