//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class ICFolderListViewController, NSString, UILabel;

@interface ICFolderListTableViewCell : UITableViewCell
{
    BOOL _needsToUpdateViews;
    ICFolderListViewController *_icaxParentFolderListViewController;
    UILabel *_titleLabel;
    UILabel *_noteCountLabel;
    NSString *_contentSizeCategory;
}

@property(copy, nonatomic) NSString *contentSizeCategory; // @synthesize contentSizeCategory=_contentSizeCategory;
@property(nonatomic) BOOL needsToUpdateViews; // @synthesize needsToUpdateViews=_needsToUpdateViews;
@property(retain, nonatomic) UILabel *noteCountLabel; // @synthesize noteCountLabel=_noteCountLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak ICFolderListViewController *_icaxParentFolderListViewController; // @synthesize _icaxParentFolderListViewController;
- (void).cxx_destruct;
@property(readonly, nonatomic) UILabel *_icaxNoteCountLabel;
@property(readonly, nonatomic) UILabel *_icaxTitleLabel;
- (BOOL)hasTrashFolder;
- (void)setSelectionStyle:(int)arg1;
- (void)updateLetterpress;
- (void)updateFonts;
- (void)resetFolderNoteCountLabel;
- (void)willMoveToWindow:(id)arg1;
- (void)updateViewsForCurrentFolder;
- (void)updateViewsForCurrentFolderIfNecessary;
- (void)prepareForReuse;
- (void)contentSizeCategoryDidChange;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)icaxToggleCellSelection;
- (id)tableTextAccessibleLabel:(id)arg1;
- (BOOL)accessibilityActivate;
- (BOOL)_accessibilitySupportsActivateAction;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;

@end

