//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ICScrollViewDelegateViewController.h"

#import "ICFolderListDelegate-Protocol.h"
#import "ICProgressIndicatorTrackerDelegate-Protocol.h"
#import "ICSearchViewControllerDelegate-Protocol.h"
#import "NSFetchedResultsControllerDelegate-Protocol.h"
#import "UISearchControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate_Deprecated-Protocol.h"

@class ICListTableView, ICNoteEditorViewController, ICNotesListCellHandler, ICNotesListSummaryView, ICProgressIndicatorTracker, ICSearchViewController, ICSelectorDelayer, NSArray, NSDate, NSFetchedResultsController, NSIndexPath, NSMutableSet, NSString, UIActivityIndicatorView, UIBarButtonItem, UILabel, UINavigationController, UIView;
@protocol ICNoteContainer, ICNotesListViewControllerDelegate, UIViewControllerPreviewing;

@interface ICNotesListViewController : ICScrollViewDelegateViewController <NSFetchedResultsControllerDelegate, UITableViewDataSource, UITableViewDelegate, ICFolderListDelegate, UISearchControllerDelegate, ICSearchViewControllerDelegate, ICProgressIndicatorTrackerDelegate, UIViewControllerPreviewingDelegate_Deprecated>
{
    BOOL _avoidNoteSelectionInViewDidAppear;
    BOOL _headerViewLabelIsSingleLine;
    BOOL _updateSelectionOnInsert;
    BOOL _autoScrollToSelectionOnNoteModification;
    BOOL _needsHidingSearchBar;
    BOOL _didReceiveContextRefreshNotification;
    BOOL _showLoadingOverlay;
    BOOL _didBeginUpdatingFromFetchedResultsController;
    BOOL _reloadDataAfterEndUpdates;
    BOOL _wasDisplayed;
    BOOL _isMovingOrDeletingNotes;
    BOOL _needsTableViewUpdates;
    BOOL _tableViewBeginUpdatesWasCalled;
    BOOL _reloadTableWhenVisible;
    BOOL _refetchAfterAttachmentBrowserDismiss;
    BOOL _setupUIComplete;
    id <ICNoteContainer> _noteContainer;
    ICNoteEditorViewController *_noteEditorViewController;
    UINavigationController *_noteEditorNavigationViewController;
    ICSearchViewController *_searchViewController;
    id <ICNotesListViewControllerDelegate> _delegate;
    NSFetchedResultsController *_fetchedResultsController;
    NSArray *_contentsCache;
    UIBarButtonItem *_attachmentButton;
    UIBarButtonItem *_summaryButton;
    UIBarButtonItem *_addNoteButton;
    UIBarButtonItem *_editButton;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_moveButton;
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_deleteAllButton;
    UIBarButtonItem *_moveAllButton;
    UIBarButtonItem *_cancelButton;
    UIBarButtonItem *_debugButton;
    NSIndexPath *_selectionPathOfDeletedNote;
    ICListTableView *_tableView;
    UIView *_loadingOverlay;
    ICNotesListSummaryView *_summaryView;
    UIActivityIndicatorView *_summarySpinnerView;
    UILabel *_headerViewLabel;
    NSIndexPath *_tableViewEditingRowIndexPath;
    NSArray *_notesToMoveToFolder;
    float _imageHeight;
    ICNotesListCellHandler *_cellHandler;
    NSMutableSet *_dirtyNotes;
    ICSelectorDelayer *_selectorDelayerForReloadData;
    ICProgressIndicatorTracker *_progressIndicatorTracker;
    unsigned int _previousSummaryViewNumNotes;
    int _generalEditModeInTransition;
    int _folderSelectorHorizontalSizeClass;
    int _currentSortType;
    id <UIViewControllerPreviewing> _previewer;
    NSDate *_lastAccessibilityAnnouncementDate;
}

@property(retain, nonatomic) NSDate *lastAccessibilityAnnouncementDate; // @synthesize lastAccessibilityAnnouncementDate=_lastAccessibilityAnnouncementDate;
@property(retain, nonatomic) id <UIViewControllerPreviewing> previewer; // @synthesize previewer=_previewer;
@property(nonatomic) BOOL setupUIComplete; // @synthesize setupUIComplete=_setupUIComplete;
@property(nonatomic) BOOL refetchAfterAttachmentBrowserDismiss; // @synthesize refetchAfterAttachmentBrowserDismiss=_refetchAfterAttachmentBrowserDismiss;
@property(nonatomic) BOOL reloadTableWhenVisible; // @synthesize reloadTableWhenVisible=_reloadTableWhenVisible;
@property(nonatomic) BOOL tableViewBeginUpdatesWasCalled; // @synthesize tableViewBeginUpdatesWasCalled=_tableViewBeginUpdatesWasCalled;
@property(nonatomic) BOOL needsTableViewUpdates; // @synthesize needsTableViewUpdates=_needsTableViewUpdates;
@property(nonatomic) BOOL isMovingOrDeletingNotes; // @synthesize isMovingOrDeletingNotes=_isMovingOrDeletingNotes;
@property(nonatomic) BOOL wasDisplayed; // @synthesize wasDisplayed=_wasDisplayed;
@property(nonatomic) int currentSortType; // @synthesize currentSortType=_currentSortType;
@property(nonatomic) int folderSelectorHorizontalSizeClass; // @synthesize folderSelectorHorizontalSizeClass=_folderSelectorHorizontalSizeClass;
@property(nonatomic) int generalEditModeInTransition; // @synthesize generalEditModeInTransition=_generalEditModeInTransition;
@property(nonatomic) BOOL reloadDataAfterEndUpdates; // @synthesize reloadDataAfterEndUpdates=_reloadDataAfterEndUpdates;
@property(nonatomic) BOOL didBeginUpdatingFromFetchedResultsController; // @synthesize didBeginUpdatingFromFetchedResultsController=_didBeginUpdatingFromFetchedResultsController;
@property(nonatomic) unsigned int previousSummaryViewNumNotes; // @synthesize previousSummaryViewNumNotes=_previousSummaryViewNumNotes;
@property(nonatomic) BOOL showLoadingOverlay; // @synthesize showLoadingOverlay=_showLoadingOverlay;
@property(retain, nonatomic) ICProgressIndicatorTracker *progressIndicatorTracker; // @synthesize progressIndicatorTracker=_progressIndicatorTracker;
@property(retain, nonatomic) ICSelectorDelayer *selectorDelayerForReloadData; // @synthesize selectorDelayerForReloadData=_selectorDelayerForReloadData;
@property(nonatomic) BOOL didReceiveContextRefreshNotification; // @synthesize didReceiveContextRefreshNotification=_didReceiveContextRefreshNotification;
@property(nonatomic) BOOL needsHidingSearchBar; // @synthesize needsHidingSearchBar=_needsHidingSearchBar;
@property(nonatomic) BOOL autoScrollToSelectionOnNoteModification; // @synthesize autoScrollToSelectionOnNoteModification=_autoScrollToSelectionOnNoteModification;
@property(retain, nonatomic) NSMutableSet *dirtyNotes; // @synthesize dirtyNotes=_dirtyNotes;
@property(retain, nonatomic) ICNotesListCellHandler *cellHandler; // @synthesize cellHandler=_cellHandler;
@property(nonatomic) float imageHeight; // @synthesize imageHeight=_imageHeight;
@property(copy, nonatomic) NSArray *notesToMoveToFolder; // @synthesize notesToMoveToFolder=_notesToMoveToFolder;
@property(nonatomic) BOOL updateSelectionOnInsert; // @synthesize updateSelectionOnInsert=_updateSelectionOnInsert;
@property(copy, nonatomic) NSIndexPath *tableViewEditingRowIndexPath; // @synthesize tableViewEditingRowIndexPath=_tableViewEditingRowIndexPath;
@property(nonatomic) BOOL headerViewLabelIsSingleLine; // @synthesize headerViewLabelIsSingleLine=_headerViewLabelIsSingleLine;
@property(retain, nonatomic) UILabel *headerViewLabel; // @synthesize headerViewLabel=_headerViewLabel;
@property(retain, nonatomic) UIActivityIndicatorView *summarySpinnerView; // @synthesize summarySpinnerView=_summarySpinnerView;
@property(retain, nonatomic) ICNotesListSummaryView *summaryView; // @synthesize summaryView=_summaryView;
@property(retain, nonatomic) UIView *loadingOverlay; // @synthesize loadingOverlay=_loadingOverlay;
@property(retain, nonatomic) ICListTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSIndexPath *selectionPathOfDeletedNote; // @synthesize selectionPathOfDeletedNote=_selectionPathOfDeletedNote;
@property(retain, nonatomic) UIBarButtonItem *debugButton; // @synthesize debugButton=_debugButton;
@property(retain, nonatomic) UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIBarButtonItem *moveAllButton; // @synthesize moveAllButton=_moveAllButton;
@property(retain, nonatomic) UIBarButtonItem *deleteAllButton; // @synthesize deleteAllButton=_deleteAllButton;
@property(retain, nonatomic) UIBarButtonItem *trashButton; // @synthesize trashButton=_trashButton;
@property(retain, nonatomic) UIBarButtonItem *moveButton; // @synthesize moveButton=_moveButton;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIBarButtonItem *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UIBarButtonItem *addNoteButton; // @synthesize addNoteButton=_addNoteButton;
@property(retain, nonatomic) UIBarButtonItem *summaryButton; // @synthesize summaryButton=_summaryButton;
@property(retain, nonatomic) UIBarButtonItem *attachmentButton; // @synthesize attachmentButton=_attachmentButton;
@property(copy, nonatomic) NSArray *contentsCache; // @synthesize contentsCache=_contentsCache;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(nonatomic) __weak id <ICNotesListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL avoidNoteSelectionInViewDidAppear; // @synthesize avoidNoteSelectionInViewDidAppear=_avoidNoteSelectionInViewDidAppear;
@property(retain, nonatomic) ICSearchViewController *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(nonatomic) __weak UINavigationController *noteEditorNavigationViewController; // @synthesize noteEditorNavigationViewController=_noteEditorNavigationViewController;
@property(retain, nonatomic) ICNoteEditorViewController *noteEditorViewController; // @synthesize noteEditorViewController=_noteEditorViewController;
@property(retain, nonatomic) id <ICNoteContainer> noteContainer; // @synthesize noteContainer=_noteContainer;
- (void).cxx_destruct;
- (BOOL)accessibilityPerformEscape;
- (void)applyAccessibilityLabels;
- (id)undoManager;
- (BOOL)canBecomeFirstResponder;
- (void)keyCommandFindNote:(id)arg1;
- (id)keyCommands;
- (BOOL)shouldShowLoadingOverlay;
- (void)noteContainerWillBeDeletedNotification:(id)arg1;
@property(readonly, nonatomic) NSArray *notes;
@property(readonly, nonatomic) BOOL shouldAlwaysHaveSelectedNoteWhenNotInEditMode;
@property(readonly, nonatomic) BOOL shouldAlwaysHaveSelectedNote;
- (void)updateSortTypeIfNecessary;
- (BOOL)isShowingFolderFromiCloudAccount;
- (void)noteDidAddOrRemovePassword:(id)arg1;
- (void)noteWillAddOrRemovePassword:(id)arg1;
- (void)delayedReloadData;
- (void)fetchAndReloadData;
- (void)currentNoteDidChange;
- (void)contentSizeCategoryDidChange;
- (void)willEnterForeground:(id)arg1;
- (void)accountsDidChange:(id)arg1;
- (void)recreateFetchedResultsControllerPerformFetch:(BOOL)arg1;
- (void)recreateFetchedResultsController;
- (void)tearDownFetchedResultsController;
- (void)updateBarButtonsAnimated:(BOOL)arg1;
- (void)updateViewsAfterNoteContainerChange;
- (void)updateNavigationTitle;
- (void)updateSelectionInTableViewAnimated:(BOOL)arg1 scrollToSelection:(BOOL)arg2;
- (void)updateSelectionInTableViewAnimated:(BOOL)arg1;
- (void)selectTableViewRowNearIndexPath:(id)arg1;
- (void)showNote:(id)arg1 scrollToRange:(struct _NSRange)arg2 animated:(BOOL)arg3;
- (void)showNote:(id)arg1 scrollToRange:(struct _NSRange)arg2;
- (void)showNote:(id)arg1 scrollToAttachment:(id)arg2 animated:(BOOL)arg3;
- (void)showNote:(id)arg1 startEditing:(BOOL)arg2;
- (void)showNote:(id)arg1;
- (void)deleteNotesFromTableView:(id)arg1 atIndexPaths:(id)arg2;
- (void)deleteNoteFromTableView:(id)arg1 atIndexPath:(id)arg2;
- (void)showFolderSelectorToMoveNotes;
- (void)closeFolderSelectorIfNeeded:(id)arg1 animated:(BOOL)arg2;
- (void)closeFolderSelector:(id)arg1;
- (id)tableViewIndexPathsForSelectedEditableRows;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)updateNavAndBarButtonsAnimated:(BOOL)arg1;
- (void)progressIndicatorTrackerStopAnimation;
- (void)progressIndicatorTrackerStartAnimation;
- (void)folderListDidCancel:(id)arg1;
- (void)moveOrDeleteNotes:(id)arg1 alertTitle:(id)arg2 alertMessage:(id)arg3 progressFormatString:(id)arg4 setupBlock:(CDUnknownBlockType)arg5 completionBlock:(CDUnknownBlockType)arg6 processNoteBlock:(CDUnknownBlockType)arg7;
- (void)moveNotes:(id)arg1 toNoteContainer:(id)arg2;
- (void)authenticateAndMoveNotes:(id)arg1 toNoteContainer:(id)arg2;
- (void)folderList:(id)arg1 didSelectNoteContainer:(id)arg2;
- (BOOL)notesFromArrayContainsUnauthenticatedNote:(id)arg1;
- (void)setNewCurrentNoteNotInNotes:(id)arg1;
- (void)folderList:(id)arg1 didSelectNoteCollection:(id)arg2 cellFrame:(struct CGRect)arg3;
- (void)summaryBarButtonPressed:(id)arg1;
- (void)noteDecryptedStatusDidChange:(id)arg1;
- (void)viewControllerWillStartEditModeNotification:(id)arg1;
- (BOOL)shouldAutorotate;
- (void)timeFormatChanged:(id)arg1;
- (void)attachmentWasDeleted:(id)arg1;
- (void)attachmentUpdated:(id)arg1;
- (void)notesContextRefreshNotification:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerWillChangeContent:(id)arg1;
- (void)showDebugMenu:(id)arg1;
- (void)moveAllNotes:(id)arg1;
- (void)deleteAllNotes:(id)arg1;
- (void)deleteSelectedNotes:(id)arg1;
- (void)moveSelectedNotes:(id)arg1;
- (void)endEditMode:(id)arg1 animated:(BOOL)arg2;
- (void)endEditMode:(id)arg1;
- (void)cancel:(id)arg1;
- (void)startEditMode:(id)arg1;
- (BOOL)isInAttachmentBrowser;
- (void)showAttachmentBrowserAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showAttachmentBrowser:(id)arg1;
- (void)addNote:(id)arg1 startEditing:(BOOL)arg2;
- (void)addNote:(id)arg1;
- (void)searchViewController:(id)arg1 didDeleteSearchResult:(id)arg2;
- (void)didDismissSearchViewController:(id)arg1;
- (void)willDismissSearchViewController:(id)arg1;
- (void)didPresentSearchViewController:(id)arg1;
- (void)willPresentSearchViewController:(id)arg1;
- (void)tableView:(id)arg1 swipeAccessoryButtonPushedForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForSwipeAccessoryButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)heightOfHeaderViewNeedTwoLines:(char *)arg1;
- (void)setHeaderViewLabelToDoubleLine;
- (void)setHeaderViewLabelToSingleLine;
- (void)setupHeaderViewLabel:(id)arg1;
- (BOOL)isInTrashFolder;
- (id)noteAtIndexPath:(id)arg1;
- (void)noteWillBeDeleted:(id)arg1;
- (void)updateAttachmentsForNotes:(id)arg1;
- (void)reloadRowForNote:(id)arg1;
- (BOOL)isVisible;
- (void)dismissSearch;
- (void)resumeAfterSuspend;
- (void)prepareForSuspend;
- (void)updateCurrentNoteEditorNote:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)splitViewControllerDidChangeHorizontalSizeClass:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)commitPreviewViewController:(id)arg1 committedViewController:(id)arg2;
- (void)didDismissPreviewViewController:(id)arg1 committing:(BOOL)arg2;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;
- (id)previewViewControllerForLocation:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (void)deleteNote:(id)arg1 atIndexPath:(id)arg2;
- (void)showUIToMoveNotes:(id)arg1;
- (void)setupUI;
- (id)contentScrollView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)hideSearchBarIfNeededAnimated:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)prepForAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

