//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface XAdMarkView : UILabel
{
    double _paddingHorizontal;
    double _paddingVertical;
    double _maxWidth;
}

@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double paddingVertical; // @synthesize paddingVertical=_paddingVertical;
@property(nonatomic) double paddingHorizontal; // @synthesize paddingHorizontal=_paddingHorizontal;
- (struct CGSize)getTextSize;
- (id)initWithFrame:(struct CGRect)arg1 fontSize:(double)arg2 textColor:(id)arg3 cornerRadius:(double)arg4 backgroundColor:(id)arg5 borderColor:(id)arg6 borderWidth:(double)arg7 paddingHorizontal:(double)arg8 paddingVertical:(double)arg9 maxWidth:(double)arg10 withText:(id)arg11;

@end

